package server

import "core:encoding/hex"
import "core:net"
import "core:sync"
import "core:testing"
import "core:thread"
import "core:time"
import "elodin:cache"
import "elodin:config"
import "elodin:dns"
import "elodin:dnssec"
import "elodin:pool"
import "elodin:upstream"

/*
An answer served insecure over the NSEC3 iteration ceiling says so, and goes on
saying so out of the cache.

RFC 9276 section 3.2 asks a resolver that answers insecure over such a record for
extended error 27, and the SERVFAIL half already had it. The insecure half is
harder than it looks: the OPT record of a forwarded or cached answer is emptied
on the way out, so nothing written into the upstream's bytes survives, and a
cache hit has no verdict of its own to read the reason from. So the code is kept
beside the entry (`cache.Entry.ede`) and attached after the strip.

The zone is `n3test.` from `src/dnssec/nsec3_name_error_test.odin`, generated by
`nsec3_name_error` in testdata/gen/sign_fixtures.py: twelve iterations, so a
validator told to accept five serves its NXDOMAIN insecure. Issue #331.
*/

@(private = "file")
C_ANCHOR :: ". IN DS 34178 15 2 5D09A200847C8691AE3E6BC2E077CB7975EA43F330D53C220AF2C6F08FA0A448"

@(private = "file")
C_QNAME :: "nx.deep.n3test."

@(private = "file")
C_Fixture :: struct {
	name: string,
	type: dns.Type,
	wire: string,
}

@(private = "file")
C_FIXTURES := []C_Fixture {
	{".", .DNSKEY, "1234858000010002000000000000300001000030000100000e1000240101030fbe2e40b9584be9eb80d709d8f4470eaa" +
		"ba4036cf474f6398a01faaa60ce8bf0b00002e000100000e10005300300f0000000e107d3b18206a4788208582002481" +
		"889066f7663c8f98048529ce749d210c4d9293900d51e1196b634f5d2deaa37ab7cfb63ec2fab3c8ac518e5a55fa6f92" +
		"ae143e4869e316efb0bd1abd9e00"},
	{"n3test.", .DS, "123485800001000200000000066e337465737400002b0001066e337465737400002b000100000e100024ce660f024c94" +
		"dbc5faf609c5970d70b7d1bd324f1f4fe52d8237a3c1bef0c40114acfb26066e337465737400002e000100000e100053" +
		"002b0f0100000e107d3b18206a478820858200774fc6ccc5ae4783d31fa22e2c1dbd90755a4814f2713d427d3d88af27" +
		"67ea5b8e76ecaa898edfbddfaa5179a5a12b47ef9dda2eb0816b1eeb744fc8c26c6902"},
	{"n3test.", .DNSKEY, "123485800001000200000000066e33746573740000300001066e3374657374000030000100000e1000240101030f89c0" +
		"39bfc7f5b52c84a4eb9d40824fe94e9dd974fe0e92a73583f73d70283354066e337465737400002e000100000e10005a" +
		"00300f0100000e107d3b18206a478820ce66066e3374657374007c28ce3b23fe670d63df1872bbc9d09d91f8e5552e7d" +
		"e32ff595ace66df8739a15334ab87c71a26752138320a646265a65b21ad376fbcd99f7ac1b2bd1ca2b0c"},
	{"nx.deep.n3test.", .A, "123485830001000000040000026e780464656570066e337465737400000100012071696b343735713237326574383572" +
		"63686d646e686c6175336b396d62626966066e3374657374000032000100000e1000250100000c020e0f14e030d26bab" +
		"04d815b54e606e8652fa125b62720e0007620000000002902071696b34373571323732657438357263686d646e686c61" +
		"75336b396d62626966066e337465737400002e000100000e10005a00320f0200000e107d3b18206a478820ce66066e33" +
		"7465737400c954c7834400fdcc99c6842667ad18fc6e5465c901b2c848cd23191efcea52b4c7f73c699c0c930227090e" +
		"c192939403b94e904222209878ebeda474951ce60c2073306f6434717462306a63316264616563316e38636b6e713239" +
		"646d34736765066e3374657374000032000100000e1000240100000c020e0f14d4a8439742389dd4176c8d9b78d55e1d" +
		"1365ae4f00064000000000022073306f6434717462306a63316264616563316e38636b6e713239646d34736765066e33" +
		"7465737400002e000100000e10005a00320f0200000e107d3b18206a478820ce66066e33746573740061295081e4f57a" +
		"e8080e3328b84ddd71852dad1eb59eaab2cb551d67286c2565b7a7aa28651e449d8763133f28d1cf54343ceef788f944" +
		"c19f294d395e12150d"},
	{"deep.n3test.", .DS, "1234858300010000000400000464656570066e337465737400002b00012071696b34373571323732657438357263686d" +
		"646e686c6175336b396d62626966066e3374657374000032000100000e1000250100000c020e0f14e030d26bab04d815" +
		"b54e606e8652fa125b62720e0007620000000002902071696b34373571323732657438357263686d646e686c6175336b" +
		"396d62626966066e337465737400002e000100000e10005a00320f0200000e107d3b18206a478820ce66066e33746573" +
		"7400c954c7834400fdcc99c6842667ad18fc6e5465c901b2c848cd23191efcea52b4c7f73c699c0c930227090ec19293" +
		"9403b94e904222209878ebeda474951ce60c2073306f6434717462306a63316264616563316e38636b6e713239646d34" +
		"736765066e3374657374000032000100000e1000240100000c020e0f14d4a8439742389dd4176c8d9b78d55e1d1365ae" +
		"4f00064000000000022073306f6434717462306a63316264616563316e38636b6e713239646d34736765066e33746573" +
		"7400002e000100000e10005a00320f0200000e107d3b18206a478820ce66066e33746573740061295081e4f57ae8080e" +
		"3328b84ddd71852dad1eb59eaab2cb551d67286c2565b7a7aa28651e449d8763133f28d1cf54343ceef788f944c19f29" +
		"4d395e12150d"},
}

// Answers each question with the fixture for its name and type, and nothing
// else; the id is the query's own.
@(private = "file")
Ceiling_Mock :: struct {
	socket: net.UDP_Socket,
	stop:   bool,
	// Reads queries and answers none, for the upstream being down.
	silent: bool,
}

@(private = "file")
ceiling_mock_serve :: proc(m: ^Ceiling_Mock) {
	buf: [4096]u8
	for !sync.atomic_load(&m.stop) {
		n, remote, err := net.recv_udp(m.socket, buf[:])
		if err != nil || n < dns.HEADER_SIZE {
			continue
		}
		query, derr := dns.decode_message(buf[:n], context.temp_allocator)
		if derr != .None || len(query.question) != 1 || sync.atomic_load(&m.silent) {
			continue
		}
		for f in C_FIXTURES {
			if f.type != query.question[0].type || !dns.name_equal_fold(f.name, query.question[0].name) {
				continue
			}
			wire, ok := hex.decode(transmute([]u8)f.wire, context.temp_allocator)
			if ok {
				wire[0], wire[1] = buf[0], buf[1]
				_, _ = net.send_udp(m.socket, wire, remote)
			}
			break
		}
		free_all(context.temp_allocator)
	}
}

@(private = "file")
ceiling_ede_of :: proc(t: ^testing.T, wire: []u8) -> (code: u16, found: bool) {
	msg, err := dns.decode_message(wire, context.temp_allocator)
	if !testing.expect(t, err == .None, "the response does not decode") {
		return 0, false
	}
	testing.expect_value(t, dns.rcode_of(msg), dns.Rcode.NX_Domain)
	testing.expect(t, !msg.flags.ad, "an insecure answer carries no AD bit")
	opt, has := dns.find_opt(msg)
	if !has {
		return 0, false
	}
	options, _ := opt.data.(dns.Rdata_OPT)
	for option in options.options {
		if option.code == u16(dns.EDNS_Option_Code.Ext_Error) && len(option.data) >= 2 {
			return u16(option.data[0]) << 8 | u16(option.data[1]), true
		}
	}
	return 0, false
}

@(test)
test_an_answer_insecure_over_the_iteration_ceiling_carries_ede_27 :: proc(t: ^testing.T) {
	mock: Ceiling_Mock
	socket, serr := net.make_bound_udp_socket(net.IP4_Loopback, 0)
	if !testing.expectf(t, serr == nil, "cannot bind the mock upstream: %v", serr) {
		return
	}
	mock.socket = socket
	defer net.close(socket)
	_ = net.set_option(socket, .Receive_Timeout, 100 * time.Millisecond)
	bound, berr := net.bound_endpoint(socket)
	if !testing.expectf(t, berr == nil, "cannot read the mock's port: %v", berr) {
		return
	}

	cfg := config.default_config()
	cfg.log.queries = false
	cfg.cache.enabled = true
	cfg.dnssec.enabled = true
	cfg.upstream.strategy = .Failover
	cfg.upstream.attempts = 1
	cfg.upstream.timeout = 1 * time.Second
	servers := make([]config.Upstream_Spec, 1, context.temp_allocator)
	servers[0] = config.Upstream_Spec {
		name    = "mock",
		kind    = .UDP,
		address = "127.0.0.1",
		port    = bound.port,
	}
	cfg.upstream.servers = servers

	g, gerr := upstream.make_group(cfg.upstream, nil)
	if !testing.expectf(t, gerr == .None, "cannot build the upstream group: %v", gerr) {
		return
	}
	defer upstream.destroy_group(g)
	// A negative TTL to fall back on: the fixture's NXDOMAIN carries no SOA, and
	// without one it would not be kept at all.
	answers := cache.make_cache(cache.Options{max_entries = 8, max_ttl = 3600, negative_ttl = 300, serve_stale = true})
	defer cache.destroy(answers)
	s := Server {
		cfg     = &cfg,
		group   = g,
		answers = answers,
	}
	anchor, parsed := dnssec.parse_trust_anchor(C_ANCHOR, context.temp_allocator)
	testing.expect(t, parsed, "the anchor should parse")
	anchors := make([]dnssec.Trust_Anchor, 1, context.temp_allocator)
	anchors[0] = anchor
	s.validator = dnssec.make_validator(validator_query, &s, dnssec.Options{anchors = anchors, max_nsec3_iterations = 5})
	defer dnssec.destroy_validator(s.validator)

	worker := thread.create_and_start_with_poly_data(&mock, ceiling_mock_serve)
	defer {
		sync.atomic_store(&mock.stop, true)
		thread.join(worker)
		thread.destroy(worker)
	}

	query := dns.Message {
		id       = 0x3131,
		question = []dns.Question{{name = C_QNAME, type = .A, class = .IN}},
	}
	query.flags.rd = true
	additional := make([]dns.Record, 1, context.temp_allocator)
	additional[0] = dns.make_opt(1232, true)
	query.additional = additional
	wire, _, eerr := dns.encode_message(query, context.temp_allocator)
	testing.expect_value(t, eerr, dns.Encode_Error.None)

	first, outcome, served := handle_query(&s, wire, .UDP, "test", context.temp_allocator)
	testing.expect(t, served, "no response for the first query")
	testing.expect_value(t, outcome, Outcome.Forwarded)
	code, found := ceiling_ede_of(t, first)
	testing.expect(t, found, "the forwarded answer carries no extended error")
	testing.expect_value(t, code, u16(EDE_UNSUPPORTED_NSEC3_ITERATIONS))

	// And from the cache, which is where the next client gets it.
	second, again, served_again := handle_query(&s, wire, .UDP, "test", context.temp_allocator)
	testing.expect(t, served_again, "no response for the second query")
	testing.expect_value(t, again, Outcome.Cached)
	code, found = ceiling_ede_of(t, second)
	testing.expect(t, found, "the cached answer lost its extended error")
	testing.expect_value(t, code, u16(EDE_UNSUPPORTED_NSEC3_ITERATIONS))

	/*
	And once the entry has expired, through both ways `cache.stale_timeout`
	answers: the refresh arriving in time, and the expired bytes when it does
	not. Declared last so it is torn down first: `pool.destroy` joins a refresh
	still waiting on the silent upstream.
	*/
	cfg.cache.serve_stale = true
	cfg.cache.stale_timeout = 2 * time.Second
	workers := pool.make_pool(2)
	defer pool.destroy(workers)
	s.handler_pool = workers
	expire :: proc(answers: ^cache.Cache) {
		for _, e in answers.entries {
			e.expires = time.time_add(time.now(), -1 * time.Second)
		}
	}

	expire(answers)
	refreshed, refreshed_outcome, served_refresh := handle_query(&s, wire, .UDP, "test", context.temp_allocator)
	testing.expect(t, served_refresh, "no response for the refreshed query")
	testing.expect_value(t, refreshed_outcome, Outcome.Forwarded)
	code, found = ceiling_ede_of(t, refreshed)
	testing.expect(t, found, "the refreshed answer lost its extended error")
	testing.expect_value(t, code, u16(EDE_UNSUPPORTED_NSEC3_ITERATIONS))

	expire(answers)
	sync.atomic_store(&mock.silent, true)
	cfg.cache.stale_timeout = 100 * time.Millisecond
	stale, stale_outcome, served_stale := handle_query(&s, wire, .UDP, "test", context.temp_allocator)
	testing.expect(t, served_stale, "no response for the stale query")
	testing.expect_value(t, stale_outcome, Outcome.Cached)
	code, found = ceiling_ede_of(t, stale)
	testing.expect(t, found, "the stale answer lost its extended error")
	testing.expect_value(t, code, u16(EDE_UNSUPPORTED_NSEC3_ITERATIONS))
}

// Only the ceiling's insecure answer gets the code, and only a client that sent
// an OPT record to put it in.
@(test)
test_ede_27_is_only_for_the_ceilings_insecure_answers :: proc(t: ^testing.T) {
	testing.expect_value(t, ceiling_ede({status = .Insecure, reason = dnssec.NSEC3_OVER_CEILING}), u16(EDE_UNSUPPORTED_NSEC3_ITERATIONS))
	testing.expect_value(t, ceiling_ede({status = .Insecure, reason = "unsigned zone"}), u16(0))
	testing.expect_value(t, ceiling_ede({status = .Secure}), u16(0))

	answer := dns.Message {
		id       = 0x3131,
		question = []dns.Question{{name = C_QNAME, type = .A, class = .IN}},
	}
	answer.flags.qr = true
	wire, _, err := dns.encode_message(answer, context.temp_allocator)
	testing.expect_value(t, err, dns.Encode_Error.None)
	plain := dns.Message {
		question = answer.question,
	}
	spent: int
	out := attach_answer_ede(wire, plain, .Forwarded, u16(EDE_UNSUPPORTED_NSEC3_ITERATIONS), 512, 1232, &spent, context.temp_allocator)
	testing.expect(t, len(out) == len(wire), "a client that sent no OPT record is given none")
	free_all(context.temp_allocator)
}
