package dnssec

import "core:mem"
import "core:testing"
import "core:time"
import "elodin:dns"

/*
Who is allowed to say that a delegation carries no DS.

The parent, and only the parent. A DS record lives in the parent zone - it is
the one type a child never publishes at its own apex - so the record a child
signs there says nothing whatever about it, and its absence from that bit map is
not a denial of anything.

Read the other way round it is the cheapest DNSSEC downgrade there is. A
malicious upstream, or anyone on the path to a plain UDP one, answers a
forwarded `DS dstest.` with NOERROR/NODATA carrying `dstest.`'s own apex NSEC and
its RRSIG, both copied verbatim from the public zone. Nothing is forged and
nothing has to be broken: the records verify against the child's keys, which this
server reached by fetching and checking the very DS it is then told does not
exist. Answering AD=1 to that tells a stub, or a downstream forwarder, that a
signed zone is an unsigned delegation, and every name under it stops being
validated.

`www` under each zone is the honest shape of the same reply - an ordinary name
that is not a zone cut, whose denial really does settle that no DS is there - and
it is here so that refusing the apex cannot quietly become refusing every DS
denial. Both zones are generated by `testdata/gen/sign_fixtures.py`, one signing
its denials with NSEC and one with NSEC3, because the bit map is read by a
separate routine for each.
*/

@(private = "file")
DA_ANCHOR :: ". IN DS 31088 15 2 2E211FFDD1AB5449FB868E6EDB29B34F33FC298FB3D007E6CEB82DD714124C2F"

@(private = "file")
DA_FIXTURES := []Fixture{
// anchor: . IN DS 31088 15 2 2E211FFDD1AB5449FB868E6EDB29B34F33FC298FB3D007E6CEB82DD714124C2F
	{
		key   = "da_root_dnskey",
		name  = ".",
		type  = .DNSKEY,
		rcode = 0,
		wire  = "1234858000010002000000000000300001000030000100000e1000240101030fca7a9002045fe086fe233b1978f853c3" +
			"6ede7b9acc2b64e6e79b472dab093aa600002e000100000e10005300300f0000000e107d3b18206a4788207970001ae1" +
			"e036edb4c45ec67fb2fdba7b0a084c6acf913ef0bae70e599bd5d25f54eb77e3ff7520a800cf5c333659cd58f1135cb8" +
			"7785c7fe15c7107d91a431fa9801",
	},
	{
		key   = "da_ds",
		name  = "dstest.",
		type  = .DS,
		rcode = 0,
		wire  = "1234858000010002000000000664737465737400002b00010664737465737400002b000100000e10002439360f02237b" +
			"db96439c6ce99949549a45c825c0233849352479df0c9409d3e62a433b460664737465737400002e000100000e100053" +
			"002b0f0100000e107d3b18206a478820797000507a061e0d622d5d72778762968e12353f91225e5fa90da32a32470e10" +
			"66ed451f6047f9b1cafad47e87f3ce9859db6e7962837c9e6cf3291ff6b3e49ccb4805",
	},
	{
		key   = "da_dnskey",
		name  = "dstest.",
		type  = .DNSKEY,
		rcode = 0,
		wire  = "12348580000100020000000006647374657374000030000106647374657374000030000100000e1000240101030f389e" +
			"f17b47174a9695b6b56dac3c41271b4bb2d493021d1e2c30e00a4fe966710664737465737400002e000100000e10005a" +
			"00300f0100000e107d3b18206a47882039360664737465737400eec3f1ab7592fa6d7ae78c31008360033d43c85b4cb8" +
			"3d7eae769ba2b8c33b62f817587d5ee019a8d228a64dff5c0b33517ac9274e8fc712bf5cb3b3b71f0200",
	},
	{
		key   = "da3_ds",
		name  = "dstest3.",
		type  = .DS,
		rcode = 0,
		wire  = "123485800001000200000000076473746573743300002b0001076473746573743300002b000100000e100024c9d90f02" +
			"9cd5ba9358d3ff1ad33808112de8ed3d2a83ffd9de70d7685071759bd5f31c55076473746573743300002e000100000e" +
			"100053002b0f0100000e107d3b18206a47882079700034881343a9bff7eee6b6b8276a99aecfd2a0e7666f04cf5916fa" +
			"22db1761d11558af35cde352126777d2353c60d6168d5a94937f8a2fcc8ac3088adec9d81b03",
	},
	{
		key   = "da3_dnskey",
		name  = "dstest3.",
		type  = .DNSKEY,
		rcode = 0,
		wire  = "123485800001000200000000076473746573743300003000010764737465737433000030000100000e1000240101030f" +
			"2bf5640b25d9767e18d0fc83eadc8223d3080a2705a2fffbd146572dc38c484e076473746573743300002e000100000e" +
			"10005b00300f0100000e107d3b18206a478820c9d9076473746573743300b11e309e05dd852e1ad2ed9fbee7013cfdfc" +
			"81ed36dda67421b987f4569a63066618dffa26092d69131e86f041adfed4fc118e70ab6272d6613d2140efdce806",
	},
	{
		key   = "bl_ds",
		name  = "bltest.",
		type  = .DS,
		rcode = 0,
		wire  = "12348580000100020000000006626c7465737400002b000106626c7465737400002b000100000e10002428750f021e19" +
			"29d2c51ca6065a3e8a75093a7dfc52abd4bc63a25f57e1a711fa5bdfdc4d06626c7465737400002e000100000e100053" +
			"002b0f0100000e107d3b18206a4788207970000f1b24be5a4f4b1dc0572a24266593fdbed027f3d1125fea2a88fefd24" +
			"93990b6051a326b04d71b430023a00a76597bb951adca8c2439876a298c84dbcc9fd0c",
	},
	{
		key   = "bl_dnskey",
		name  = "bltest.",
		type  = .DNSKEY,
		rcode = 0,
		wire  = "12348580000100020000000006626c74657374000030000106626c74657374000030000100000e1000240101030f13c7" +
			"7f51c78b8333fd853b85039723a938e362a3354af1ed00083b89a57a427706626c7465737400002e000100000e10005a" +
			"00300f0100000e107d3b18206a478820287506626c74657374002c422a3855fb644d884b36778ab6dc8ae38b74636917" +
			"9f2928ca99c63a7477d1b41fd87138b86d0f5158ed0c45b149a163db6feb884c701889d361caa8e43807",
	},
	{
		key   = "da_apex_nodata",
		name  = "dstest.",
		type  = .DS,
		rcode = 0,
		wire  = "1234858000010000000200000664737465737400002b00010664737465737400002f000100000e100015037777770664" +
			"7374657374000007620000000003800664737465737400002e000100000e10005a002f0f0100000e107d3b18206a4788" +
			"203936066473746573740080f098fdae04c0334cd8cfbf70cc80a6cde515d51537df3fff50b5923cdfb6bb00b7152117" +
			"f52fb8a4459280e18792ff17c62bfc7c834d25159db68f42259806",
	},
	{
		key   = "da_www_nodata",
		name  = "www.dstest.",
		type  = .DS,
		rcode = 0,
		wire  = "123485800001000000020000037777770664737465737400002b0001037777770664737465737400002f000100000e10" +
			"001006647374657374000006400000000003037777770664737465737400002e000100000e10005a002f0f0200000e10" +
			"7d3b18206a47882039360664737465737400a939f17b7201e26a18ae5b11ee1d92109d6e0a6c8546ef65ca293e05bbaa" +
			"8814d7eeedcf7039f15acc5162f4c3664c700b2ab3de282b17ca2f2bba4f4e26d109",
	},
	{
		key   = "da3_apex_nodata",
		name  = "dstest3.",
		type  = .DS,
		rcode = 0,
		wire  = "123485800001000000020000076473746573743300002b00012062306d757661653765703675617664666e6b68616d34" +
			"343138623570373830620764737465737433000032000100000e10002501000000020a0b14ecede9435140cb3b9e8482" +
			"308464c19e3b59cd710007620000000002902062306d757661653765703675617664666e6b68616d3434313862357037" +
			"383062076473746573743300002e000100000e10005b00320f0200000e107d3b18206a478820c9d90764737465737433" +
			"0028da2e7547c49b866789e55d8c20c1aca74f6a9712fe3bf673f1c903f2262b9fc38754ac6247eaa9580052daae0e79" +
			"943b558cb2e9665c273dddc8e229a7a701",
	},
	{
		key   = "da3_www_nodata",
		name  = "www.dstest3.",
		type  = .DS,
		rcode = 0,
		wire  = "12348580000100000002000003777777076473746573743300002b000120746a6d75696771683833356a6e376b346738" +
			"6f38387036316a6f746c6a6a62680764737465737433000032000100000e10002401000000020a0b14582defa9c7764d" +
			"e57dafbd22ab108142cb93a00b000640000000000220746a6d75696771683833356a6e376b3467386f38387036316a6f" +
			"746c6a6a6268076473746573743300002e000100000e10005b00320f0200000e107d3b18206a478820c9d90764737465" +
			"73743300712ec0f32fdd7d46caf9aa05646b31b6c5b8411f0ccac80ed0a8c1930deea11bac35118b2b16460a4cd8ba2a" +
			"088a07c5cb6c615b0c8591d4d0c444fa83511205",
	},
	{
		key   = "bl_apex_nodata",
		name  = "bltest.",
		type  = .DS,
		rcode = 0,
		wire  = "12348580000100000002000006626c7465737400002b000106626c7465737400002f000100000e100012016106626c74" +
			"65737400000600000000000306626c7465737400002e000100000e10005a002f0f0100000e107d3b18206a4788202875" +
			"06626c7465737400ea6fa83f54677f32464f6f29ca4a3c0dbe19890bce16ab3d6c7eb35edc07e0eafdc02888694a86d9" +
			"8c903ade3fe21d05593194720ca21e4325ac465083440a06",
	},
}

@(private = "file")
da_query :: proc(ctx: rawptr, name: string, type: dns.Type, allocator: mem.Allocator) -> (wire: []u8, ok: bool) {
	// The genuine DS and DNSKEY fixtures are listed before the denials, so the
	// chain walk finds the delegation rather than the reply under test.
	for f in DA_FIXTURES {
		if f.type == type && dns.name_equal_fold(f.name, name) {
			return decode_hex(f.wire, allocator)
		}
	}
	return nil, false
}

@(private = "file")
da_validator :: proc() -> ^Validator {
	anchor, ok := parse_trust_anchor(DA_ANCHOR, context.temp_allocator)
	if !ok {
		return nil
	}
	anchors := make([]Trust_Anchor, 1, context.temp_allocator)
	anchors[0] = anchor
	return make_validator(da_query, nil, Options{anchors = anchors})
}

@(private = "file")
da_reply :: proc(key: string) -> []u8 {
	for f in DA_FIXTURES {
		if f.key == key {
			out, _ := decode_hex(f.wire, context.temp_allocator)
			return out
		}
	}
	return nil
}

@(private = "file")
da_validate :: proc(key, qname: string) -> Result {
	v := da_validator()
	if v == nil {
		return {status = .Indeterminate, reason = "the anchor did not parse"}
	}
	defer destroy_validator(v)
	return validate(v, qname, .DS, da_reply(key), time.unix(FIXTURE_TIME, 0))
}

@(test)
test_a_ds_denial_carried_by_the_childs_own_apex_nsec_is_bogus :: proc(t: ^testing.T) {
	result := da_validate("da_apex_nodata", "dstest.")
	testing.expectf(
		t,
		result.status == .Bogus,
		"a zone's own apex NSEC cannot deny the DS its parent holds, got %v (%q)",
		result.status,
		result.reason,
	)
	free_all(context.temp_allocator)
}

@(test)
test_a_ds_denial_carried_by_the_childs_own_apex_nsec3_is_bogus :: proc(t: ^testing.T) {
	result := da_validate("da3_apex_nodata", "dstest3.")
	testing.expectf(
		t,
		result.status == .Bogus,
		"a zone's own apex NSEC3 cannot deny the DS its parent holds, got %v (%q)",
		result.status,
		result.reason,
	)
	free_all(context.temp_allocator)
}

@(test)
test_a_ds_denial_from_the_zone_itself_is_bogus_whatever_the_bit_map_says :: proc(t: ^testing.T) {
	/*
	The same attack from a signer that leaves nothing on the record to catch it
	by.

	RFC 4470 lets a zone answer NODATA with an NSEC minted for the question
	instead of one taken from its chain, and a signer doing that has no reason
	to put SOA or NS on it. `bltest.` publishes exactly that at its own apex:
	no DS, no SOA, no NS. An attacker fetches it once with a harmless query and
	replays it verbatim as the authority section of a NODATA answer to
	`DS bltest.` - and both bit-map guards stand down, because there is nothing
	in the bit map for them to read.

	What settles it is not in the response at all. `zone_trust` walked down to
	`bltest.` and established it, which for a DS question means `zone_step`
	fetched the DS at that name and checked it against the parent's keys. A
	denial of the DS that got us here contradicts the work that made the answer
	readable, and no record an attacker can send changes that.

	So this is the test for that check on its own: the bit-map guard cannot pass
	it, and the unit tests in `nsec_unit_test` and `nsec3_unit_test` call the two
	routines directly, so neither layer can quietly stand in for the other.
	*/
	result := da_validate("bl_apex_nodata", "bltest.")
	testing.expectf(
		t,
		result.status == .Bogus,
		"a zone cannot deny the DS this server followed to reach it, got %v (%q)",
		result.status,
		result.reason,
	)
	free_all(context.temp_allocator)
}

@(test)
test_a_ds_denial_at_a_name_that_is_not_a_zone_cut_still_holds :: proc(t: ^testing.T) {
	// The control for both of the above. `www.dstest.` is an ordinary name in a
	// signed zone: no NS, no SOA, and no DS, which its NSEC states outright.
	result := da_validate("da_www_nodata", "www.dstest.")
	testing.expectf(
		t,
		result.status == .Secure,
		"an NSEC at an ordinary name still denies a DS, got %v (%q)",
		result.status,
		result.reason,
	)
	free_all(context.temp_allocator)
}

@(test)
test_a_ds_denial_at_a_name_that_is_not_a_zone_cut_still_holds_under_nsec3 :: proc(t: ^testing.T) {
	result := da_validate("da3_www_nodata", "www.dstest3.")
	testing.expectf(
		t,
		result.status == .Secure,
		"an NSEC3 at an ordinary name still denies a DS, got %v (%q)",
		result.status,
		result.reason,
	)
	free_all(context.temp_allocator)
}
