package dnssec

import "core:mem"
import "core:testing"
import "core:time"
import "elodin:dns"

/*
A signed cut below a step the ceiling kept the parent's keys past.

`c3test.` hashes twelve times and a validator told to accept five cannot read
the DS denial at the empty non-terminal `e.c3test.`, so the walk keeps
`c3test.`'s keys past it and records that it did (`Budget.walk_past_ceiling`).
Below it `s.e.c3test.` is a DS the parent signed, and from there the walk is
reading a zone it established - so a forgery there is a forgery, and the flag
has to have been let go of. Generated by `nsec3_signed_cut_below_ceiling` in
testdata/gen/sign_fixtures.py. Issue #331.
*/

@(private = "file")
C3_ANCHOR :: ". IN DS 60029 15 2 1B9C87A4B7CF5267C99E13250A9A503F075D27986A393EDF6DC842A7CD3A683D"

@(private = "file")
C3_FIXTURES := []Fixture{
	{
		key   = "c3_root_dnskey",
		name  = ".",
		type  = .DNSKEY,
		rcode = 0,
		wire  = "1234858000010002000000000000300001000030000100000e1000240101030f3f63181da096aa9e35307ba08ce71147" +
			"b74144cd30b5db6e39bfd1d2187ec87500002e000100000e10005300300f0000000e107d3b18206a478820ea7d0036c7" +
			"8292aa3e8e9cdf18b38510066372c2807c0561881c3db0f879afdb536cc09a846199f05d1ab7be84ea9b156a4f227fb3" +
			"7e39096104122b5b36e9011c3e08",
	},
	{
		key   = "c3_ds",
		name  = "c3test.",
		type  = .DS,
		rcode = 0,
		wire  = "1234858000010002000000000663337465737400002b00010663337465737400002b000100000e100024efa70f02a921" +
			"e5cfa4e109bb0995c49c96fdd520edae8110ac973a71e9f85ececd929f400663337465737400002e000100000e100053" +
			"002b0f0100000e107d3b18206a478820ea7d00ce04eb10ef5d0ab89eb595a44f6c30861e252e2935b2035c583051b0fb" +
			"1f870d75552cb0fd6275c1966d63a44adab9f0cabea2d4f6a11037dcb2ed841a6d650c",
	},
	{
		key   = "c3_dnskey",
		name  = "c3test.",
		type  = .DNSKEY,
		rcode = 0,
		wire  = "12348580000100020000000006633374657374000030000106633374657374000030000100000e1000240101030f1654" +
			"2eb3f57cc3f8943e9c2b229a14654350cf321572f1e0fe265cfa333cdd7d0663337465737400002e000100000e10005a" +
			"00300f0100000e107d3b18206a478820efa706633374657374001aa11ebe8212ab3e6deff83461a5b3f9fef7ed69ad86" +
			"aa6b854cbc029dd76f3affb2d73abeb59a3d5d416fcd845ee3a7b28ec9eb10e734ae9fde9d9ace238c04",
	},
	{
		key   = "c3_ent_ds",
		name  = "e.c3test.",
		type  = .DS,
		rcode = 0,
		wire  = "12348580000100000002000001650663337465737400002b000120726a713464343633356e69716434336f3776683873" +
			"336463386275356837736f06633374657374000032000100000e10001c0100000c020e0f143d2bc79fd9cd3ffc1a1bb6" +
			"b31cb1710099a5390d20726a713464343633356e69716434336f3776683873336463386275356837736f066333746573" +
			"7400002e000100000e10005a00320f0200000e107d3b18206a478820efa70663337465737400e530e54592d73217f051" +
			"842ab60254e77fe10312bdb432c1ad74ef1970ed7c9c603a5dd6c55e69358dba18ae2ae96eaf14d846a09b2e70649d9e" +
			"6f57ebf30a0a",
	},
	{
		key   = "c3_child_ds",
		name  = "s.e.c3test.",
		type  = .DS,
		rcode = 0,
		wire  = "123485800001000200000000017301650663337465737400002b0001017301650663337465737400002b000100000e10" +
			"0024b1840f027438e1ed720574f9107183bac928de969756dafe08de5d1f4e2647d2a4be91ca01730165066333746573" +
			"7400002e000100000e10005a002b0f0300000e107d3b18206a478820efa706633374657374001a31c25e2936ac28d9c1" +
			"84e8d1ddb51a5438e2588786b71065f14646bca3002ba7f746c1bec85281069f68269907aed03499b48949d90c57e7cd" +
			"4ccc9aa08901",
	},
	{
		key   = "c3_child_dnskey",
		name  = "s.e.c3test.",
		type  = .DNSKEY,
		rcode = 0,
		wire  = "123485800001000200000000017301650663337465737400003000010173016506633374657374000030000100000e10" +
			"00240101030f4a6675dd1e66efc8fef5f366b08641a682514df2dcf441ffd4ac26d64cf3c2c901730165066333746573" +
			"7400002e000100000e10005e00300f0300000e107d3b18206a478820b184017301650663337465737400ba300c0fc9f5" +
			"79470f0adee2af7776c6b0608d47111672f389527056072e7561b8dd92cad892c4bb17921d665b984287e8e24d1bbf7c" +
			"de1c85ac96e2cfc4c70d",
	},
	{
		key   = "c3_answer",
		name  = "s.e.c3test.",
		type  = .A,
		rcode = 0,
		wire  = "123485800001000200000000017301650663337465737400000100010173016506633374657374000001000100000e10" +
			"0004c0000235017301650663337465737400002e000100000e10005e00010f0300000e107d3b18206a478820b1840173" +
			"01650663337465737400df51e496cc2f5c4ce8620e3f575dae30473ce13495ab05b3e5cb36787ba61679d5904d593793" +
			"c77b779daf891995e0a47f2c48481e1f61e05c665d5454870d06",
	},
}

@(private = "file")
c3_query :: proc(ctx: rawptr, name: string, type: dns.Type, allocator: mem.Allocator) -> (wire: []u8, ok: bool) {
	for f in C3_FIXTURES {
		if f.type == type && dns.name_equal_fold(f.name, name) {
			return decode_hex(f.wire, allocator)
		}
	}
	return nil, false
}

@(private = "file")
c3_wire :: proc(key: string) -> []u8 {
	for f in C3_FIXTURES {
		if f.key == key {
			out, _ := decode_hex(f.wire, context.temp_allocator)
			return out
		}
	}
	return nil
}

@(test)
test_a_signed_cut_below_the_ceiling_is_judged_on_its_own_keys :: proc(t: ^testing.T) {
	anchor, parsed := parse_trust_anchor(C3_ANCHOR, context.temp_allocator)
	testing.expect(t, parsed, "the anchor should parse")
	anchors := make([]Trust_Anchor, 1, context.temp_allocator)
	anchors[0] = anchor
	now := time.unix(FIXTURE_TIME, 0)

	// The child's own signed answer validates: the step the ceiling could not
	// read did not stop the walk reaching the zone that signed it.
	v := make_validator(c3_query, nil, Options{anchors = anchors, max_nsec3_iterations = 5})
	defer destroy_validator(v)
	signed := validate(v, "s.e.c3test.", .A, c3_wire("c3_answer"), now)
	testing.expectf(t, signed.status == .Secure, "the child's signed answer should validate, got %v (%q)", signed.status, signed.reason)

	// The same answer stripped of its signature is a forgery in a zone this
	// walk read, and is called one rather than blamed on the ceiling above.
	msg, err := dns.decode_message(c3_wire("c3_answer"), context.temp_allocator)
	testing.expect(t, err == .None, "the fixture should decode")
	unsigned := make([dynamic]dns.Record, context.temp_allocator)
	for rr in msg.answer {
		if rr.type != .RRSIG {
			append(&unsigned, rr)
		}
	}
	msg.answer = unsigned[:]
	wire, _, encode_err := dns.encode_message(msg, context.temp_allocator)
	testing.expect_value(t, encode_err, dns.Encode_Error.None)

	fresh := make_validator(c3_query, nil, Options{anchors = anchors, max_nsec3_iterations = 5})
	defer destroy_validator(fresh)
	forged := validate(fresh, "s.e.c3test.", .A, wire, now)
	testing.expectf(t, forged.status == .Bogus, "a forgery below a signed cut is bogus, got %v (%q)", forged.status, forged.reason)
	free_all(context.temp_allocator)
}
