# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-22 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NamesDatabase', '0002_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip_usuario',
            field=models.CharField(default='127.0.0.1', max_length=255),
            preserve_default=False,
        ),
    ]
