# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NamesDatabase', '0003_log_ip_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
